# libs.versions.toml

[versions]
agp = "8.13.0" # Версія Android Gradle Plugin
drawerlayout = "1.2.0"
gson = "2.13.2"
hiltAndroid = "2.57.2"
kotlin = "2.2.20" # Версія Kotlin
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4" # Залишаємо, оскільки Lifecycle часто використовується і з Views
appcompat = "1.7.1"
material = "1.13.0" # Для com.google.android.material:material
activity = "1.11.0"
constraintlayout = "2.2.1"
roomVersion = "2.8.2"
voskAndroidVersion = "0.3.70"
ambilwarna = "2.0.1"
ksp = "2.2.20-2.0.3"
hilt = "2.57.2"
hilt-navigation-fragment = "1.3.0"
documentfile = "1.0.1"


[libraries]
# AndroidX Core
alphacephei-vosk-android = { module = "com.alphacephei:vosk-android", version.ref = "voskAndroidVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
hilt-navigation-fragment = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "hilt-navigation-fragment" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

# JUnit для тестів
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ambilwarna = { module = "com.github.yukuku:ambilwarna", version.ref = "ambilwarna" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Бібліотеки AndroidX та Material Design
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }